#!/usr/bin/env bash
# manages manage_my_process

case $1 in
	start)
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	
	stop)
		kill "$(cat /var/run/my_process.pid)" && rm -rf /var/run/my_process.pid
		echo "manage my process stopped"
		;;

	restart)
		kill "$(cat /var/run/my_process.pid)" && rm -rf /var/run/my_process.pid
		sleep 1
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;

esac	
