#!/usr/bin/env bash
# displays:
#	To infinity and beyond indefinitely
#	With a sleep 2 in between each iteration
#	I am invincible!!! when receiving a SIGTERM signal

# infinite loop
while true; do
	echo "To infinity and beyond"
	sleep 2

	# Function to handle SIGTERM
	trap 'echo "I am invincible!!!";' SIGTERM
done
